### ISSUE TITLE
Is there any prepared MCMD data to directly use with CoDisum?

### ISSUE THREAD

**Issue by soroushjavdan** [DeepSoftwareAnalytics/CommitMsgEmpirical#1]
First, I would like to congratulate you on your interesting research and thank you for your contribution.

I wanted to run CoDiSum with MCMD data (not only java) but apparently, there are some steps required to transform the MCMD data in a form that can be fed to CoDiSum. I wonder if you publish or have a plan to publish a version of MCMD that can be directly fed to the CoDisum or the code to do the transformation?

Thanks is advance for your help.

**Comment by itaowei** [comment]
Thank you for your attention to our research work!

Here is a [script ](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/main/dataset/other_dataset_preprocessing/data4CopynetV3.py) which can be used to do the transformation as you described.

For example, if you want to transform MCMD_cpp to fit CoDiSum model, you can run below,

```
raw_data_path= <the path where you store the uncompressed `raw_data.tar.gz`>
lan=cpp # this variable can be changed to  'java', 'csharp', 'python', and 'javascript'
python data4CopynetV3.py -rl dataset/repo_list.json -in $raw_data_path -out preprocessed_data/MCMD/ -s random --need_time -lan $lan
```
(Note: `raw_data.tar.gz` can be downloaded from this [link](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/tree/main/dataset#raw-data) and its information [here](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/tree/main/dataset))

More information about this script can be seen by ` python data4CopynetV3.py --help`

**Comment by soroushjavdan** [comment]
@itaowei Thanks for your quick reply.
I add the data_process_tools.py to the project from CoDiSum project since you import it at the first line of the data4CopynetV3 code. However, it wasn't able to find line_filter_cmt, can you please let me know very can I find it?

Thanks is advance for your help.

**Comment by itaowei** [comment]
> Thanks for your quick reply. I add the data_process_tools.py to the project from CoDiSum project since you import it at the first line of the data4CopynetV3 code. However, it wasn't able to find line_filter_cmt, can you please let me know very can I find it?
> 
> Thanks is advance for your help.

I am sorry that I ignored these functions that this file depends on. I updated [`data4CopynetV3.py`](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/main/dataset/other_dataset_preprocessing/data4CopynetV3.py) right now.
If you have any questions, feel free to contact me!

Thanks for your kind reply!

**Comment by soroushjavdan** [comment]
Thanks a lot for your help.
