### ISSUE TITLE
CommitGen(CmtGen) 源码

### ISSUE THREAD

**Issue by xwh130** [DeepSoftwareAnalytics/CommitMsgEmpirical#2]
您好，这个[CommitGen(CmtGen)](https://sjiang1.github.io/commitgen/)代码原作者好像删了，请问您有这个工作的源码吗？

**Comment by itaowei** [comment]
感谢您对我们工作的关注！CommitGen(CmtGen)这篇工作的代码可以在第一作者的个人主页里找到：首先访问[https://sjiang1.github.io](https://sjiang1.github.io) ，然后，如下图所示，点击菜单里的「COMMITGEN」即可正常访问 https://sjiang1.github.io/commitgen。
![Screenshot_2022-11-10-12-12-35-321_com microsoft emmx-edit](https://user-images.githubusercontent.com/19475586/200999262-311f2a9b-aadd-4291-b7c8-51a46631bd33.jpg)

**Comment by xwh130** [comment]
感谢您的提示
