### ISSUE TITLE
How to preprocess dataset on a new programming language?

### ISSUE THREAD

**Issue by asxzhy** [DeepSoftwareAnalytics/CommitMsgEmpirical#3]
Hi, 

I want to obtain a filtered Go commit message dataset similar to the other five programming languages in the MCMD dataset.

I already have the raw Go commit message dataset following the same structure shown in the dataset [readme](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/a18d531d3aeb8a6bf51d37a4aad0a11e401906a5/dataset/ReadMe.md#raw-data). 

Right now, I am trying to modify this [data4CopynetV3.py](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/a18d531d3aeb8a6bf51d37a4aad0a11e401906a5/dataset/other_dataset_preprocessing/data4CopynetV3.py) script that is provided in the dataset section so that I can preprocess the raw data. However, I am stuck in the method `build_word2index2()` which reads a `lemmatization.json` json file. I cannot find the file and I don't see where it is generated.

Could you please help me on this issue? Also, I would like to know is this `data4CopynetV3.py` script used for getting the filtered data in MCMD dataset? Just to make sure that I am going in the correct direction.

Thank you!

**Comment by itaowei** [comment]
Thank you for your attention to our research work!

The [data4CopynetV3.py](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/a18d531d3aeb8a6bf51d37a4aad0a11e401906a5/dataset/other_dataset_preprocessing/data4CopynetV3.py) is used to preprocess MCMD to apply to [CoDiSum](https://github.com/SoftWiser-group/CoDiSum), which means it is not the script to preprocess MCMD<sub>raw</sub> to MCMD<sub>filtered</sub>.

To make this clear, we have added the [`lemmatization.json`](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/main/dataset/other_dataset_preprocessing/lemmatization.json) to our repo and add a [README.md](https://github.com/DeepSoftwareAnalytics/CommitMsgEmpirical/blob/main/dataset/other_dataset_preprocessing/README.md).

As described in the paper, we followed the filtering method<sup>[1]</sup>. More details can be found in the paper(especially Section 4.2 and Appendix).

[1] Y. Jiang, X. Xia, G. Zhang and D. Lo, "Neural-Machine-Translation-Based Commit Message Generation: How Far Are We?," 2019 IEEE/ACM 41st International Conference on Software Engineering (ICSE), Montreal, QC, Canada, 2019, pp. 1143-1154, doi: 10.1109/ICSE.2019.00119.

Hope the above information can help you : )

**Comment by asxzhy** [comment]
Thank you! I will look into it!
